title: TukTuk
author: Archana Kalburgi
email: archanakalburgi@gmail.com
description: >- 
  TukTuk is a personal blog about my personal projects, learnings, and experiences in the world of technology.

url: "https://archanakalburgi.github.io"
baseurl: "/tuktuk"

theme: minima

# Enable blog features  
show_excerpts: true

# Optional: Add a navigation menu
minima:
  social_links:
    - { platform: github, 
        user_url: "https://github.com/archanakalburgi" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
